
# sudo su -
# hostname k8s-proxy 
# echo "k8s-proxy" > /etc/hostname  
# bash

- hosts: all

  handlers:
    - name: "restart haproxy"
      service:
        name: haproxy
        state: restarted
      become: yes

  tasks:

    - name: "Roda: sudo apt-get update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia

    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - haproxy

    - name: "Trocando haproxy"
      copy:
        src: "haproxy/haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"
      become: yes
      notify:
        - "restart haproxy"


# ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ~/Desktop/devops/treinamentoItau
# ssh -i ~/Desktop/devops/treinamentoItau ubuntu@ec2-54-152-41-46.compute-1.amazonaws.com
# systemctl status haproxy | less
